const RouteNames = {
  home: "/",
  term: "/terms-and-conditions",
  policy: "/privacy-policy",
  about: "/about-us",
  contact: "/contact-us",
  get_started: "/get-started",
  blog: "/blog",
  blog_detail: "/blog/:id",
  resource_tools: "/resources/tools-guides",
  resouce_story: "/resources/success-stories",
  resource_hub: "/resources/customer-hub",
  resource_faq: "/resources/faqs",
  resources: "/resources",
  pricing_addons: "/pricing-plans/add-ons",
  pricing: "/pricing-plans",
  staffs: "/features/staff-management",
  feature_tables: "/features/table-management",
  feature_menus: "/features/menu-management",
  feature_waitlist: "/features/waitlist-management",
  feature_reservations: "/features/reservations",
  features: "/features",
  why_boost: "/why-boost",
  snapfood_network: "/snapfood-network",
  not_found: "/not-found",
  whoweserve_restaurants: "/who-we-serve/restaurants",
  whoweserve_cafes: "/who-we-serve/cafes",
  whoweserve_bistros: "/who-we-serve/bistros",
  whoweserve_bars: "/who-we-serve/bars",
  whoweserve_pubandclubs: "/who-we-serve/pub-and-clubs",
};

export default RouteNames;
